[build-system]
# Specify the build dependencies and backend
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agnostic-controller"
version = "0.2.0"
description = "Agnostic Robotic Controller Project"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "numpy",
    "scipy"
]
license = { file = "LICENSE" }

keywords = ["robotics", "socket", "control", "automation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
where = ["."] 
include = ["agnostic_controller*"] 
exclude = ["tests*"]

[project.urls]
Homepage = "https://github.com/MGross21/agnostic-controller"
Tracker = "https://github.com/MGross21/agnostic-controller/issues"
