[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "agnostic-controller"
version = "0.2.0"
description = "Agnostic Robotic Controller Project"
packages = [{ include = "agnostic_controller" }]
authors = [ { name = "Michael Gross", email = "MGross21@TODO.com" } ]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.6,<4.0"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib"
]
keywords = ["robotics", "socket", "control", "automation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
where = ["."] 
include = ["agnostic_controller*"] 
exclude = ["tests*"]

[project.urls]
Homepage = "https://github.com/MGross21/agnostic-controller"
Tracker = "https://github.com/MGross21/agnostic-controller/issues"
