[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "armctl"
version = "0.3.0"
description = "Agnostic Robotic Manipulator Controller"
packages = [{ include = "armctl" }]
authors = [ { name = "Michael Gross", email = "MGross21@TODO.com" } ]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.6,<4.0"
dependencies = []
keywords = ["robotics", "socket", "control", "automation"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
where = ["."] 
include = ["armctl*"] 
exclude = ["tests*"]

[project.urls]
Homepage = "https://github.com/MGross21/armctl"
Tracker = "https://github.com/MGross21/armctl/issues"
